"""change hash to id

Revision ID: 6b1b9f691d95
Revises: 407e93bbe08c
Create Date: 2024-04-20 00:30:35.108252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1b9f691d95'
down_revision = '407e93bbe08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crash_bets', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crash_bets', 'crash_hashes', ['game_id'], ['id'])
    op.drop_column('crash_bets', 'game_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crash_bets', sa.Column('game_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'crash_bets', type_='foreignkey')
    op.drop_column('crash_bets', 'game_id')
    # ### end Alembic commands ###
