"""add wallet

Revision ID: 7bc1d6a9e1d5
Revises: 6756d830931f
Create Date: 2024-04-22 20:49:16.154962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc1d6a9e1d5'
down_revision = '6756d830931f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_address')
    # ### end Alembic commands ###
