"""add post_url

Revision ID: a78ad2f1de61
Revises: b01b0bd59b6d
Create Date: 2024-04-24 19:50:28.269897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78ad2f1de61'
down_revision = 'b01b0bd59b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_posts', sa.Column('post_url', sa.String(), nullable=True))
    op.alter_column('twitter_posts', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_posts', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('twitter_posts', 'post_url')
    # ### end Alembic commands ###
