"""create_hashes_state_bets

Revision ID: abfaa3442f3b
Revises: 8f99ec9023b0
Create Date: 2024-04-19 00:10:02.524228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abfaa3442f3b'
down_revision = '8f99ec9023b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash_hashes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crash_bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_hash', sa.String(), nullable=True),
    sa.Column('cash_out_multiplier', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('current_game_hash_id', sa.Integer(), nullable=True),
    sa.Column('last_game_hash_id', sa.Integer(), nullable=True),
    sa.Column('last_game_result', sa.Float(), nullable=True),
    sa.Column('next_game_time', sa.DateTime(), nullable=False),
    sa.Column('betting_close_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_game_hash_id'], ['crash_hashes.id'], ),
    sa.ForeignKeyConstraint(['last_game_hash_id'], ['crash_hashes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_state')
    op.drop_table('crash_bets')
    op.drop_table('crash_hashes')
    # ### end Alembic commands ###
