"""make prev game nullable

Revision ID: e7e880f57eff
Revises: 4ef16a09f8fb
Create Date: 2024-05-15 16:21:00.276002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e880f57eff'
down_revision = '4ef16a09f8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
