"""save access token

Revision ID: f77ed6e25140
Revises: a78ad2f1de61
Create Date: 2024-04-25 01:22:21.146000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77ed6e25140'
down_revision = 'a78ad2f1de61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('access_token_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_token_secret')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
